(function(g){var window=this;'use strict';var Tft=function(B){B.publish("autonavvisibility")},LKM=function(B,M){B.EC("onAutonavCoundownStarted",M)},X8u=function(B){var M,q,D;
return B==null?void 0:(M=B.playerOverlays)==null?void 0:(q=M.playerOverlayRenderer)==null?void 0:(D=q.autoplay)==null?void 0:D.playerOverlayAutoplayRenderer},Mq=function(B,M,q){g.ep(B.element,"ytp-suggestion-set",!!M.videoId);
var D=M.playlistId;q=M.tA(q?q:"mqdefault.jpg");var O=null,C=null;M instanceof g.mG&&(M.lengthText?(O=M.lengthText||null,C=M.L0||null):M.lengthSeconds&&(O=g.Zq(M.lengthSeconds),C=g.Zq(M.lengthSeconds,!0)));var K=!!D;D=K&&g.Ze(D).type==="RD";var E=M instanceof g.mG?M.isLivePlayback:null,v=M instanceof g.mG?M.isUpcoming:null,F=M.author,b=M.shortViewCount,u=M.publishedTimeText,J=[],A=[];F&&J.push(F);b&&(J.push(b),A.push(b));u&&A.push(u);q={title:M.title,author:F,author_and_views:J.join(" \u2022 "),aria_label:M.ariaLabel||
g.zZ("\u89c0\u770b\u300c$TITLE\u300d",{TITLE:M.title}),duration:O,timestamp:C,url:M.VS(),is_live:E,is_upcoming:v,is_list:K,is_mix:D,background:q?"background-image: url("+q+")":"",views_and_publish_time:A.join(" \u2022 "),autoplayAlternativeHeader:M.m3};M instanceof g.jW&&(q.playlist_length=M.playlistLength);B.update(q)},qq=function(B){var M=B.S(),q=M.W;
g.T.call(this,{j:"a",L:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:q?M.U:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},N:[{j:"div",fR:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},N:[{j:"div",X:{"aria-label":"{{timestamp}}"},fR:["ytp-autonav-timestamp"],Th:"{{duration}}"},{j:"div",fR:["ytp-autonav-live-stamp"],Th:"\u76f4\u64ad"},
{j:"div",fR:["ytp-autonav-upcoming-stamp"],Th:"\u5373\u5c07\u64ad\u51fa"},{j:"div",L:"ytp-autonav-list-overlay",N:[{j:"div",L:"ytp-autonav-mix-text",Th:"\u5408\u8f2f"},{j:"div",L:"ytp-autonav-mix-icon"}]}]},{j:"div",fR:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Th:"{{title}}"},{j:"div",fR:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Th:"{{author}}"},{j:"div",fR:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],Th:"{{views_and_publish_time}}"}]});
this.Z=B;this.suggestion=null;this.C=q;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},DH=function(B,M){M=M===void 0?!1:M;
g.T.call(this,{j:"div",L:"ytp-autonav-endscreen-countdown-overlay"});var q=this;this.D=M;this.cancelCommand=this.K=void 0;this.B=0;this.container=new g.T({j:"div",L:"ytp-autonav-endscreen-countdown-container"});g.p(this,this.container);this.container.MG(this.element);M=B.S();var D=M.W;this.Z=B;this.suggestion=null;this.onVideoDataChange("newdata",g.Q(this.Z.getVideoData()));this.V(B,"videodatachange",this.onVideoDataChange);this.C=new g.T({j:"div",L:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},N:[{j:"div",L:"ytp-autonav-endscreen-upnext-header"},{j:"div",L:"ytp-autonav-endscreen-upnext-alternative-header",Th:"{{autoplayAlternativeHeader}}"},{j:"a",L:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:D?M.U:""},N:[{j:"div",L:"ytp-autonav-endscreen-upnext-thumbnail",X:{style:"{{background}}"},N:[{j:"div",X:{"aria-label":"{{timestamp}}"},fR:["ytp-autonav-timestamp"],
Th:"{{duration}}"},{j:"div",fR:["ytp-autonav-live-stamp"],Th:"\u76f4\u64ad"},{j:"div",fR:["ytp-autonav-upcoming-stamp"],Th:"\u5373\u5c07\u64ad\u51fa"}]},{j:"div",L:"ytp-autonav-endscreen-video-info",N:[{j:"div",L:"ytp-autonav-endscreen-premium-badge"},{j:"div",L:"ytp-autonav-endscreen-upnext-title",Th:"{{title}}"},{j:"div",L:"ytp-autonav-endscreen-upnext-author",Th:"{{author}}"},{j:"div",L:"ytp-autonav-view-and-date",Th:"{{views_and_publish_time}}"},{j:"div",L:"ytp-autonav-author-and-view",Th:"{{author_and_views}}"}]}]}]});
g.p(this,this.C);this.C.MG(this.container.element);D||this.V(this.C.l5("ytp-autonav-endscreen-link-container"),"click",this.t2);this.Z.createClientVe(this.container.element,this,115127);this.Z.createClientVe(this.C.l5("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.T({j:"div",L:"ytp-autonav-overlay"});g.p(this,this.overlay);this.overlay.MG(this.container.element);this.T=new g.T({j:"div",L:"ytp-autonav-endscreen-button-container"});g.p(this,this.T);this.T.MG(this.container.element);
this.cancelButton=new g.T({j:"button",fR:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",M.G("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"\u53d6\u6d88\u81ea\u52d5\u64ad\u653e"},Th:"\u53d6\u6d88"});g.p(this,this.cancelButton);this.cancelButton.MG(this.T.element);this.cancelButton.listen("click",this.dJ,this);this.Z.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.T({j:"a",fR:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button",M.G("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"\u64ad\u653e\u4e0b\u4e00\u90e8\u5f71\u7247"},Th:"\u7acb\u5373\u64ad\u653e"});g.p(this,this.playButton);this.playButton.MG(this.T.element);this.playButton.listen("click",this.t2,this);this.Z.createServerVe(this.playButton.element,this.playButton,!0);(M=this.Z.getVideoData())&&w8t(this,M);this.W=new g.LP(function(){sko(q)},500);
g.p(this,this.W);this.Da();this.V(B,"autonavvisibility",this.Da);this.Z.G("web_autonav_color_transition")&&(this.V(B,"autonavchange",this.Hi),this.V(B,"onAutonavCoundownStarted",this.B6r))},Ou=function(B){var M=B.Z.yR(!0,B.Z.isFullscreen());
g.ep(B.container.element,"ytp-autonav-endscreen-small-mode",B.Qg(M));g.ep(B.container.element,"ytp-autonav-endscreen-is-premium",!!B.suggestion&&!!B.suggestion.JAC);g.ep(B.Z.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!B.Z.Dh());g.ep(B.Z.getRootNode(),"countdown-running",B.FR());g.ep(B.container.element,"ytp-player-content",B.Z.Dh());g.HV(B.overlay.element,{width:M.width+"px"});if(!B.FR()){B.Z.Dh()?R0e(B,Math.round(iDT(B)/1E3)):R0e(B);M=!!B.suggestion&&!!B.suggestion.m3;var q=B.Z.Dh()||
!M;g.ep(B.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!q&&M);g.ep(B.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",q&&!M);B.T.Co(B.Z.Dh());g.ep(B.element,"ytp-enable-w2w-color-transitions",rRL(B))}},sko=function(B){var M=iDT(B),q=Math,D=q.min;
var O=B.B?Date.now()-B.B:0;q=D.call(q,O,M);R0e(B,Math.ceil((M-q)/1E3));M-q<=500&&B.FR()?B.select(!0):B.FR()&&B.W.start()},iDT=function(B){if(B.Z.isFullscreen()){var M;
B=(M=B.Z.getVideoData())==null?void 0:M.Ro;return B===-1||B===void 0?8E3:B}return B.Z.rN()>=0?B.Z.rN():g.ui(B.Z.S().experiments,"autoplay_time")||1E4},w8t=function(B,M){M=M.getWatchNextResponse();
var q,D;M=(q=X8u(M))==null?void 0:(D=q.nextButton)==null?void 0:D.buttonRenderer;B.K=M==null?void 0:M.navigationEndpoint;q=M==null?void 0:M.trackingParams;B.playButton&&q&&B.Z.setTrackingParams(B.playButton.element,q)},rRL=function(B){var M;
return!((M=B.Z.getVideoData())==null||!M.watchToWatchTransitionRenderer)},R0e=function(B,M){M=M===void 0?-1:M;
B=B.C.l5("ytp-autonav-endscreen-upnext-header");g.MI(B);if(M>=0){M=String(M);var q="\u4e0b\u4e00\u90e8\u5f71\u7247\u5c07\u5728 $SECONDS \u79d2\u5f8c\u64ad\u653e".match(RegExp("\\$SECONDS","gi"))[0],D="\u4e0b\u4e00\u90e8\u5f71\u7247\u5c07\u5728 $SECONDS \u79d2\u5f8c\u64ad\u653e".indexOf(q);if(D>=0){B.appendChild(g.aO("\u4e0b\u4e00\u90e8\u5f71\u7247\u5c07\u5728 $SECONDS \u79d2\u5f8c\u64ad\u653e".slice(0,D)));var O=g.xU("span");g.Mv(O,"ytp-autonav-endscreen-upnext-header-countdown-number");g.CA(O,M);
B.appendChild(O);B.appendChild(g.aO("\u4e0b\u4e00\u90e8\u5f71\u7247\u5c07\u5728 $SECONDS \u79d2\u5f8c\u64ad\u653e".slice(D+q.length)));return}}g.CA(B,"\u5373\u5c07\u64ad\u653e")},CS=function(B,M){g.T.call(this,{j:"div",
fR:["html5-endscreen","ytp-player-content",M||"base-endscreen"]});this.created=!1;this.player=B},KS=function(B){g.T.call(this,{j:"div",
fR:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},N:[{j:"div",L:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{j:"span",L:"ytp-upnext-top",N:[{j:"span",L:"ytp-upnext-header",Th:"\u5373\u5c07\u64ad\u653e"},{j:"span",L:"ytp-upnext-title",Th:"{{title}}"},{j:"span",L:"ytp-upnext-author",Th:"{{author}}"}]},{j:"a",L:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"\u64ad\u653e\u4e0b\u4e00\u90e8\u5f71\u7247"},N:[{j:"svg",X:{height:"100%",version:"1.1",
viewBox:"0 0 72 72",width:"100%"},N:[{j:"circle",L:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{j:"circle",L:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{j:"path",L:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{j:"span",L:"ytp-upnext-bottom",N:[{j:"span",L:"ytp-upnext-cancel"},
{j:"span",L:"ytp-upnext-paused",Th:"\u5df2\u66ab\u505c\u81ea\u52d5\u64ad\u653e\u529f\u80fd"}]}]});this.api=B;this.cancelButton=null;this.K=this.l5("ytp-svg-autoplay-ring");this.B=this.notification=this.C=this.suggestion=null;this.W=new g.LP(this.UL,5E3,this);this.T=0;var M=this.l5("ytp-upnext-cancel");this.cancelButton=new g.T({j:"button",fR:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"\u53d6\u6d88\u81ea\u52d5\u64ad\u653e"},Th:"\u53d6\u6d88"});g.p(this,this.cancelButton);
this.cancelButton.listen("click",this.rJ,this);this.cancelButton.MG(M);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.p(this,this.W);this.api.createClientVe(this.element,this,18788);M=this.l5("ytp-upnext-autoplay-icon");this.V(M,"click",this.RR);this.api.createClientVe(M,this,115130);this.mm();this.V(B,"autonavvisibility",this.mm);this.V(B,"mdxnowautoplaying",this.HoL);this.V(B,"mdxautoplaycanceled",this.dNr);g.ep(this.element,"ytp-upnext-mobile",this.api.S().T)},
xZd=function(B,M){if(M)return M;
if(B.api.isFullscreen()){var q;B=(q=B.api.getVideoData())==null?void 0:q.Ro;return B===-1||B===void 0?8E3:B}return B.api.rN()>=0?B.api.rN():g.ui(B.api.S().experiments,"autoplay_time")||1E4},avZ=function(B,M){M=xZd(B,M);
var q=Math,D=q.min;var O=(0,g.f)()-B.T;q=D.call(q,O,M);M=M===0?1:Math.min(q/M,1);B.K.setAttribute("stroke-dashoffset",""+-211*(M+1));M>=1&&B.FR()&&B.api.getPresentingPlayerType()!==3?B.select(!0):B.FR()&&B.C.start()},eU=function(B){CS.call(this,B,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.T({j:"div",L:"ytp-suggestion-panel",N:[{j:"div",fR:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Th:"\u66f4\u591a\u5f71\u7247"}]});this.Y=new g.T({j:"div",L:"ytp-suggestions-container"});this.videos=[];this.B=null;this.K=this.D=!1;this.T=new DH(this.player);g.p(this,this.T);this.T.MG(this.element);B.getVideoData().UZ?this.C=this.T:(this.C=new KS(B),g.Hs(this.player,this.C.element,4),g.p(this,this.C));this.overlay=new g.T({j:"div",
L:"ytp-autonav-overlay-cancelled-state"});g.p(this,this.overlay);this.overlay.MG(this.element);this.W=new g.td(this);g.p(this,this.W);g.p(this,this.table);this.table.MG(this.element);this.table.show();g.p(this,this.Y);this.Y.MG(this.table.element);this.hide()},oe=function(B){var M=B.Dh();
M!==B.K&&(B.K=M,Tft(B.player),B.K?(B.T!==B.C&&B.T.hide(),B.table.hide()):(B.T!==B.C&&B.T.show(),B.table.show()))},Eu=function(B,M){g.T.call(this,{j:"button",
fR:["ytp-watch-on-youtube-button","ytp-button"],Th:"{{content}}"});this.Z=B;this.buttonType=this.buttonType=M;this.DG();this.buttonType===2&&g.D8(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.DG);this.Co(!0)},vg=function(B,M){CS.call(this,B,"embeds-lite-endscreen");
this.Z=B;this.C=M;this.Z.createClientVe(this.element,this,156943);this.watchButton=new Eu(B,2);g.p(this,this.watchButton);this.watchButton.MG(this.element);this.hide()},Fs=function(B){var M=B.S(),q=g.WE||g.Vi?{style:"will-change: opacity"}:void 0,D=M.W,O=["ytp-modern-videowall-still"];
M.T&&O.push("ytp-videowall-show-text");g.T.call(this,{j:"a",fR:O,X:{href:"{{url}}",target:D?M.U:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},N:[{j:"div",L:"ytp-modern-videowall-still-image",X:{style:"{{background}}"},N:[{j:"span",L:"ytp-modern-videowall-still-info-duration",Th:"{{duration}}"}]},{j:"span",L:"ytp-modern-videowall-still-info",X:{"aria-hidden":"true"},N:[{j:"span",L:"ytp-modern-videowall-still-info-bg",N:[{j:"span",
L:"ytp-modern-videowall-still-info-content",X:q,N:[{j:"span",L:"ytp-modern-videowall-still-info-title",Th:"{{title}}"},{j:"span",L:"ytp-modern-videowall-still-info-author",Th:"{{author_and_views}}"},{j:"span",L:"ytp-modern-videowall-still-info-live",Th:"\u76f4\u64ad"}]}]}]},{j:"span",fR:["ytp-modern-videowall-still-listlabel-regular","ytp-modern-videowall-still-listlabel"],X:{"aria-hidden":"true"},N:[{j:"span",L:"ytp-modern-videowall-still-listlabel-icon"},"\u64ad\u653e\u6e05\u55ae",{j:"span",L:"ytp-modern-videowall-still-listlabel-length",
N:[" (",{j:"span",Th:"{{playlist_length}}"},")"]}]},{j:"span",fR:["ytp-modern-videowall-still-listlabel-mix","ytp-modern-videowall-still-listlabel"],X:{"aria-hidden":"true"},N:[{j:"span",L:"ytp-modern-videowall-still-listlabel-mix-icon"},"\u5408\u8f2f",{j:"span",L:"ytp-modern-videowall-still-listlabel-length",Th:" (50+)"}]}]});this.suggestion=null;this.T=D;this.api=B;this.C=new g.td(this);g.p(this,this.C);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.C.V(B,"videodatachange",
this.onVideoDataChange);B.createServerVe(this.element,this);this.onVideoDataChange()},Bcj=function(B){CS.call(this,B,"videowall-endscreen");
var M=this;this.Z=B;this.stills=[];this.B=this.videoData=null;this.W=this.D=!1;this.Y=null;g.D8(this.element,"modern-videowall-endscreen");this.T=new g.td(this);g.p(this,this.T);this.K=new g.LP(function(){g.D8(M.element,"ytp-show-tiles")},0);
g.p(this,this.K);this.table=new g.v3({j:"div",L:"ytp-modern-endscreen-content"});g.p(this,this.table);this.table.MG(this.element);B.getVideoData().UZ?this.C=new DH(B,!0):this.C=new KS(B);g.p(this,this.C);g.Hs(this.player,this.C.element,4);B.createClientVe(this.element,this,158789);this.hide()},bM=function(B){return g.U6(B.player)&&B.D9()&&!B.B},uM=function(B){var M=B.Dh();
M!==B.D&&(B.D=M,Tft(B.player))},Mtj=function(B){CS.call(this,B,"subscribecard-endscreen");
this.C=new g.T({j:"div",L:"ytp-subscribe-card",N:[{j:"img",L:"ytp-author-image",X:{src:"{{profilePicture}}"}},{j:"div",L:"ytp-subscribe-card-right",N:[{j:"div",L:"ytp-author-name",Th:"{{author}}"},{j:"div",L:"html5-subscribe-button-container"}]}]});g.p(this,this.C);this.C.MG(this.element);var M=B.getVideoData();this.subscribeButton=new g.TI("\u8a02\u95b1",null,"\u53d6\u6d88\u8a02\u95b1",null,!0,!1,M.f7,M.subscribed,"trailer-endscreen",null,B,!1);g.p(this,this.subscribeButton);this.subscribeButton.MG(this.C.l5("html5-subscribe-button-container"));
this.V(B,"videodatachange",this.a4);this.a4();this.hide()},Ja=function(B){var M=B.S(),q=g.WE||g.Vi?{style:"will-change: opacity"}:void 0,D=M.W,O=["ytp-videowall-still"];
M.T&&O.push("ytp-videowall-show-text");g.T.call(this,{j:"a",fR:O,X:{href:"{{url}}",target:D?M.U:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},N:[{j:"div",L:"ytp-videowall-still-image",X:{style:"{{background}}"}},{j:"span",L:"ytp-videowall-still-info",X:{"aria-hidden":"true"},N:[{j:"span",L:"ytp-videowall-still-info-bg",N:[{j:"span",L:"ytp-videowall-still-info-content",X:q,N:[{j:"span",L:"ytp-videowall-still-info-title",Th:"{{title}}"},
{j:"span",L:"ytp-videowall-still-info-author",Th:"{{author_and_views}}"},{j:"span",L:"ytp-videowall-still-info-live",Th:"\u76f4\u64ad"},{j:"span",L:"ytp-videowall-still-info-duration",Th:"{{duration}}"}]}]}]},{j:"span",fR:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},N:[{j:"span",L:"ytp-videowall-still-listlabel-icon"},"\u64ad\u653e\u6e05\u55ae",{j:"span",L:"ytp-videowall-still-listlabel-length",N:[" (",{j:"span",Th:"{{playlist_length}}"},")"]}]},
{j:"span",fR:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},N:[{j:"span",L:"ytp-videowall-still-listlabel-mix-icon"},"\u5408\u8f2f",{j:"span",L:"ytp-videowall-still-listlabel-length",Th:" (50+)"}]}]});this.suggestion=null;this.T=D;this.api=B;this.C=new g.td(this);g.p(this,this.C);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.C.V(B,"videodatachange",this.onVideoDataChange);B.createServerVe(this.element,this);this.onVideoDataChange()},
Aa=function(B){CS.call(this,B,"videowall-endscreen");
var M=this;this.Z=B;this.B=0;this.stills=[];this.W=this.videoData=null;this.K=this.Y=!1;this.U=null;this.T=new g.td(this);g.p(this,this.T);this.D=new g.LP(function(){g.D8(M.element,"ytp-show-tiles")},0);
g.p(this,this.D);var q=new g.T({j:"button",fR:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"\u4e0a\u4e00\u90e8"},N:[g.hF()]});g.p(this,q);q.MG(this.element);q.listen("click",this.Cc,this);this.table=new g.v3({j:"div",L:"ytp-endscreen-content"});g.p(this,this.table);this.table.MG(this.element);q=new g.T({j:"button",fR:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"\u4e0b\u4e00\u500b"},N:[g.yM()]});g.p(this,q);q.MG(this.element);q.listen("click",this.vG,this);B.getVideoData().UZ?this.C=
new DH(B,!0):this.C=new KS(B);g.p(this,this.C);g.Hs(this.player,this.C.element,4);B.createClientVe(this.element,this,158789);this.hide()},Nq=function(B){return g.U6(B.player)&&B.D9()&&!B.W},zk=function(B){var M=B.Dh();
M!==B.Y&&(B.Y=M,Tft(B.player))},$w=function(B){CS.call(this,B,"watch-again-on-youtube-endscreen");
this.watchButton=new Eu(B,1);g.p(this,this.watchButton);this.watchButton.MG(this.element);g.xOL(B)&&(this.C=new g.wR(B),g.p(this,this.C),this.T=new g.T({j:"div",fR:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},N:[this.C]}),g.p(this,this.T),this.C.MG(this.T.element),this.T.MG(this.element));B.createClientVe(this.element,this,156914);this.hide()},Cju=function(B){g.v_.call(this,B);
var M=this;this.endScreen=null;this.T=this.C=this.B=this.W=!1;this.listeners=new g.td(this);g.p(this,this.listeners);var q=B.S(),D=B.getVideoData();D=D&&D.limitedPlaybackDurationInSeconds!==0;g.EY(g.th(q))&&D&&!g.lH(B)?(this.T=!0,this.endScreen=new vg(B,g.$G(B))):B.isEmbedsShortsMode()?this.endScreen=new $w(B):qWM(B)?(this.W=!0,DEN(this),this.C?this.endScreen=new eU(B):q.G("delhi_modern_endscreen")?this.endScreen=new Bcj(B):this.endScreen=new Aa(B)):q.Vz?this.endScreen=new Mtj(B):this.endScreen=new CS(B);
g.p(this,this.endScreen);g.Hs(B,this.endScreen.element,4);Obj(this);this.listeners.V(B,"videodatachange",this.onVideoDataChange,this);this.listeners.V(B,g.K8("endscreen"),function(O){M.onCueRangeEnter(O)});
this.listeners.V(B,g.e5("endscreen"),function(O){M.onCueRangeExit(O)})},DEN=function(B){var M=B.player.getVideoData();
if(!M||B.C===M.qY&&B.B===M.UZ)return!1;B.C=M.qY;B.B=M.UZ;return!0},qWM=function(B){B=B.S();
return B.RC&&!B.Vz&&!B.disableOrganicUi},Obj=function(B){B.player.VI("endscreen");
var M=B.player.getVideoData();M=new g.Ol(Math.max((M.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var q=new g.Ol(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});B.player.pg([M,q])};
g.gL.prototype.rN=g.KZ(14,function(){return this.app.rN()});
g.F6.prototype.rN=g.KZ(13,function(){return this.getVideoData().J3});
g.jY.prototype.e8=g.KZ(12,function(B){this.SI().e8(B)});
g.Oa.prototype.e8=g.KZ(11,function(B){this.C!==B&&(this.C=B,this.a4())});
g.kz.prototype.e8=g.KZ(10,function(B){this.overflowButton&&this.overflowButton.e8(B)});
g.jY.prototype.Tn=g.KZ(9,function(B){this.SI().Tn(B)});
g.vA.prototype.Tn=g.KZ(8,function(B){this.T!==B&&(this.T=B,this.a4())});
g.kz.prototype.Tn=g.KZ(7,function(B){this.shareButton&&this.shareButton.Tn(B)});
g.jY.prototype.uE=g.KZ(6,function(B){this.SI().uE(B)});
g.H_.prototype.uE=g.KZ(5,function(B){this.n_!==B&&(this.n_=B,this.I1())});
g.jY.prototype.ZH=g.KZ(4,function(B){this.SI().ZH(B)});
g.kz.prototype.ZH=g.KZ(3,function(B){this.p_!==B&&(this.p_=B,this.zP())});g.z(qq,g.T);qq.prototype.select=function(){this.Z.iC(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Ck||void 0)&&this.Z.logClick(this.element)};
qq.prototype.onClick=function(B){g.oV(B,this.Z,this.C,this.suggestion.sessionData||void 0)&&this.select()};
qq.prototype.onKeyPress=function(B){switch(B.keyCode){case 13:case 32:B.defaultPrevented||(this.select(),B.preventDefault())}};g.z(DH,g.T);g.e=DH.prototype;g.e.lZ=function(B){this.suggestion!==B&&(this.suggestion=B,Mq(this.C,B),this.playButton.updateValue("url",this.suggestion.VS()),Ou(this))};
g.e.FR=function(){return this.B>0};
g.e.DW=function(){this.FR()||(this.B=Date.now(),sko(this),LKM(this.Z,iDT(this)),g.ep(this.Z.getRootNode(),"countdown-running",this.FR()))};
g.e.vI=function(){this.sJ();sko(this);var B=this.C.l5("ytp-autonav-endscreen-upnext-header");B&&g.CA(B,"\u5373\u5c07\u64ad\u653e")};
g.e.sJ=function(){this.FR()&&(this.W.stop(),this.B=0)};
g.e.select=function(B){this.Z.nextVideo(!1,B===void 0?!1:B);this.sJ()};
g.e.t2=function(B){g.oV(B,this.Z)&&(B.currentTarget===this.playButton.element?this.Z.logClick(this.playButton.element):B.currentTarget===this.C.l5("ytp-autonav-endscreen-link-container")&&(B=this.C.l5("ytp-autonav-endscreen-link-container"),this.Z.logVisibility(B,!0),this.Z.logClick(B)),this.K?(this.Z.EC("innertubeCommand",this.K),this.sJ()):this.select())};
g.e.dJ=function(){this.Z.logClick(this.cancelButton.element);g.Gh(this.Z,!0);this.cancelCommand&&this.Z.EC("innertubeCommand",this.cancelCommand)};
g.e.onVideoDataChange=function(B,M){w8t(this,M);B=M.getWatchNextResponse();var q,D;B=(q=X8u(B))==null?void 0:(D=q.cancelButton)==null?void 0:D.buttonRenderer;this.cancelCommand=B==null?void 0:B.command};
g.e.B6r=function(B){if(rRL(this)){var M=this.Z.getVideoData().watchToWatchTransitionRenderer,q=M==null?void 0:M.fromColorPaletteDark;M=M==null?void 0:M.toColorPaletteDark;if(q&&M){var D=this.element;D.style.setProperty("--w2w-start-background-color",g.tp(q.surgeColor));D.style.setProperty("--w2w-start-primary-text-color",g.tp(q.primaryTitleColor));D.style.setProperty("--w2w-start-secondary-text-color",g.tp(q.secondaryTitleColor));D.style.setProperty("--w2w-end-background-color",g.tp(M.surgeColor));
D.style.setProperty("--w2w-end-primary-text-color",g.tp(M.primaryTitleColor));D.style.setProperty("--w2w-end-secondary-text-color",g.tp(M.secondaryTitleColor));D.style.setProperty("--w2w-animation-duration",B+"ms")}g.ep(this.element,"ytp-w2w-animate",!0)}};
g.e.Hi=function(B){this.Z.G("web_autonav_color_transition")&&B!==2&&g.ep(this.element,"ytp-w2w-animate",!1)};
g.e.Da=function(){var B=this.Z.Dh();this.D&&this.vE!==B&&this.Co(B);Ou(this);this.Z.logVisibility(this.container.element,B);this.Z.logVisibility(this.cancelButton.element,B);this.Z.logVisibility(this.C.l5("ytp-autonav-endscreen-link-container"),B);this.Z.logVisibility(this.playButton.element,B)};
g.e.Qg=function(B){return B.width<400||B.height<459};g.z(CS,g.T);g.e=CS.prototype;g.e.create=function(){this.created=!0};
g.e.destroy=function(){this.created=!1};
g.e.D9=function(){return!1};
g.e.Dh=function(){return!1};
g.e.uX=function(){return!1};g.z(KS,g.T);g.e=KS.prototype;g.e.UL=function(){this.notification&&(this.W.stop(),this.J0(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.e.lZ=function(B){this.suggestion=B;Mq(this,B,"hqdefault.jpg")};
g.e.mm=function(){this.Co(this.api.Dh());this.api.logVisibility(this.element,this.api.Dh());this.api.logVisibility(this.l5("ytp-upnext-autoplay-icon"),this.api.Dh());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.Dh())};
g.e.hAG=function(){window.focus();this.UL()};
g.e.DW=function(B){var M=this;this.FR()||(g.C3("a11y-announce","\u5373\u5c07\u64ad\u653e "+this.suggestion.title),this.T=(0,g.f)(),this.C=new g.LP(function(){avZ(M,B)},25),avZ(this,B),LKM(this.api,xZd(this,B)));
g.C7(this.element,"ytp-upnext-autoplay-paused")};
g.e.hide=function(){g.T.prototype.hide.call(this)};
g.e.FR=function(){return!!this.C};
g.e.vI=function(){this.sJ();this.T=(0,g.f)();avZ(this);g.D8(this.element,"ytp-upnext-autoplay-paused")};
g.e.sJ=function(){this.FR()&&(this.C.dispose(),this.C=null)};
g.e.select=function(B){B=B===void 0?!1:B;if(this.api.S().G("autonav_notifications")&&B&&window.Notification&&typeof document.hasFocus==="function"){var M=Notification.permission;M==="default"?Notification.requestPermission():M!=="granted"||document.hasFocus()||(this.UL(),this.notification=new Notification("\u5373\u5c07\u64ad\u653e",{body:this.suggestion.title,icon:this.suggestion.tA()}),this.B=this.V(this.notification,"click",this.hAG),this.W.start())}this.sJ();this.api.nextVideo(!1,B)};
g.e.RR=function(B){!g.O8(this.cancelButton.element,B.target)&&g.oV(B,this.api)&&(this.api.Dh()&&this.api.logClick(this.l5("ytp-upnext-autoplay-icon")),this.select())};
g.e.rJ=function(){this.api.Dh()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.Gh(this.api,!0)};
g.e.HoL=function(B){this.api.getPresentingPlayerType();this.show();this.DW(B)};
g.e.dNr=function(){this.api.getPresentingPlayerType();this.sJ();this.hide()};
g.e.eY=function(){this.sJ();this.UL();g.T.prototype.eY.call(this)};g.z(eU,CS);g.e=eU.prototype;g.e.create=function(){CS.prototype.create.call(this);this.W.V(this.player,"appresize",this.QU);this.W.V(this.player,"onVideoAreaChange",this.QU);this.W.V(this.player,"videodatachange",this.onVideoDataChange);this.W.V(this.player,"autonavchange",this.PH);this.W.V(this.player,"onAutonavCancelled",this.Xh);this.onVideoDataChange()};
g.e.show=function(){CS.prototype.show.call(this);(this.D||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.Gh(this.player,!1);g.U6(this.player)&&this.D9()&&!this.B?(oe(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.C.select(!0):this.C.DW():this.videoData.autonavState===3&&this.C.vI()):(g.Gh(this.player,!0),oe(this));this.QU()};
g.e.hide=function(){CS.prototype.hide.call(this);this.C.vI();oe(this)};
g.e.QU=function(){var B=this.player.yR(!0,this.player.isFullscreen());oe(this);Ou(this.T);g.ep(this.element,"ytp-autonav-cancelled-small-mode",this.Qg(B));g.ep(this.element,"ytp-autonav-cancelled-tiny-mode",this.m4(B));g.ep(this.element,"ytp-autonav-cancelled-mini-mode",B.width<=400||B.height<=360);this.overlay&&g.HV(this.overlay.element,{width:B.width+"px"});if(!this.K)for(B=0;B<this.videos.length;B++)g.ep(this.videos[B].element,"ytp-suggestion-card-with-margin",B%2===1)};
g.e.onVideoDataChange=function(){var B=this.player.getVideoData();if(this.videoData!==B&&B){this.videoData=B;if((B=this.videoData.suggestions)&&B.length||this.player.G("web_player_autonav_empty_suggestions_fix")){var M=g.Bk(this.videoData);M&&(this.C.lZ(M),this.C!==this.T&&this.T.lZ(M))}if(B&&B.length)for(M=0;M<K5M.length;++M){var q=K5M[M];if(B&&B[q]){this.videos[M]=new qq(this.player);var D=this.videos[M];q=B[q];D.suggestion!==q&&(D.suggestion=q,Mq(D,q));g.p(this,this.videos[M]);this.videos[M].MG(this.Y.element)}}this.QU()}};
g.e.PH=function(B){B===1?(this.D=!1,this.B=this.videoData.clientPlaybackNonce,this.C.sJ(),this.vE&&this.QU()):(this.D=!0,this.Dh()&&(B===2?this.C.DW():B===3&&this.C.vI()))};
g.e.Xh=function(B){B?this.PH(1):(this.B=null,this.D=!1)};
g.e.D9=function(){return this.videoData.autonavState!==1};
g.e.Qg=function(B){return(B.width<910||B.height<459)&&!this.m4(B)&&!(B.width<=400||B.height<=360)};
g.e.m4=function(B){return B.width<800&&!(B.width<=400||B.height<=360)};
g.e.Dh=function(){return this.vE&&g.U6(this.player)&&this.D9()&&!this.B};
var K5M=[1,3,2,4];g.z(Eu,g.T);g.e=Eu.prototype;g.e.DG=function(){switch(this.buttonType){case 1:var B="\u5728 YouTube \u4e0a\u518d\u6b21\u89c0\u770b";var M=156915;break;case 2:B="\u524d\u5f80 YouTube \u7e7c\u7e8c\u89c0\u770b";M=156942;break;default:B="\u524d\u5f80 YouTube \u7e7c\u7e8c\u89c0\u770b",M=156942}this.update({content:B});this.Z.hasVe(this.element)&&this.Z.destroyVe(this.element);this.Z.createClientVe(this.element,this,M)};
g.e.onClick=function(B){this.Z.G("web_player_log_click_before_generating_ve_conversion_params")&&this.Z.logClick(this.element);g.Ei(this.getVideoUrl(),this.Z,B);this.Z.G("web_player_log_click_before_generating_ve_conversion_params")||this.Z.logClick(this.element)};
g.e.getVideoUrl=function(){var B=!0;switch(this.buttonType){case 1:B=!0;break;case 2:B=!1}B=this.Z.getVideoUrl(B,!1,!1,!0);var M=this.Z.S();if(g.dY(M)){var q={};g.dY(M)&&g.uH(this.Z,"addEmbedsConversionTrackingParams",[q]);B=g.ld(B,q)}return B};
g.e.logVisibility=function(){this.Z.logVisibility(this.element,this.vE&&this.J)};
g.e.show=function(){g.T.prototype.show.call(this);this.logVisibility()};
g.e.hide=function(){g.T.prototype.hide.call(this);this.logVisibility()};
g.e.L3=function(B){g.T.prototype.L3.call(this,B);this.logVisibility()};g.z(vg,CS);vg.prototype.show=function(){this.player.getPlayerState()!==3&&(CS.prototype.show.call(this),this.C.ZH(!0),this.C.Tn(!0),this.Z.S().Jk||this.C.e8(!0),this.Z.logVisibility(this.element,!0),this.watchButton.L3(!0))};
vg.prototype.hide=function(){CS.prototype.hide.call(this);this.C.ZH(!1);this.C.Tn(!1);this.C.e8(!1);this.Z.logVisibility(this.element,!1);this.watchButton.L3(!1)};g.z(Fs,g.T);Fs.prototype.select=function(){this.api.iC(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Ck||void 0)&&this.api.logClick(this.element)};
Fs.prototype.onClick=function(B){if(g.dY(this.api.S())&&this.api.G("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var M=this.suggestion.VS(),q={};g.I$(this.api,q);M=g.ld(M,q);g.Ei(M,this.api,B)}else g.oV(B,this.api,this.T,this.suggestion.sessionData||void 0)&&this.select()};
Fs.prototype.onKeyPress=function(B){switch(B.keyCode){case 13:case 32:B.defaultPrevented||(this.select(),B.preventDefault())}};
Fs.prototype.onVideoDataChange=function(){var B=this.api.getVideoData(),M=this.api.S();this.T=B.yN?!1:M.W};g.z(Bcj,CS);g.e=Bcj.prototype;g.e.create=function(){CS.prototype.create.call(this);var B=this.player.getVideoData();B&&(this.videoData=B);this.rC();this.T.V(this.player,"appresize",this.rC);this.T.V(this.player,"onVideoAreaChange",this.rC);this.T.V(this.player,"videodatachange",this.onVideoDataChange);this.T.V(this.player,"autonavchange",this.ZP);this.T.V(this.player,"onAutonavCancelled",this.U2);B=this.videoData.autonavState;B!==this.Y&&this.ZP(B);this.T.V(this.element,"transitionend",this.pc)};
g.e.destroy=function(){g.gM(this.T);g.bZ(this.stills);this.stills=[];CS.prototype.destroy.call(this);g.C7(this.element,"ytp-show-tiles");this.K.stop();this.Y=this.videoData.autonavState};
g.e.D9=function(){return this.videoData.autonavState!==1};
g.e.show=function(){var B=this.vE;CS.prototype.show.call(this);g.C7(this.element,"ytp-show-tiles");this.player.S().T?g.Rb(this.K):this.K.start();(this.W||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.Gh(this.player,!1);bM(this)?(uM(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.C.select(!0):this.C.DW():this.videoData.autonavState===3&&this.C.vI()):(g.Gh(this.player,!0),uM(this));B!==this.vE&&this.player.logVisibility(this.element,!0)};
g.e.hide=function(){var B=this.vE;CS.prototype.hide.call(this);this.C.vI();uM(this);B!==this.vE&&this.player.logVisibility(this.element,!1)};
g.e.pc=function(B){B.target===this.element&&this.rC()};
g.e.rC=function(){var B,M,q,D;var O=((B=this.videoData)==null?0:(M=B.suggestions)==null?0:M.length)?(q=this.videoData)==null?void 0:q.suggestions:[(D=this.videoData)==null?void 0:g.Bk(D)];if(O.length){M=this.Z.yR(!0,this.Z.isFullscreen());B=Math.floor((M.width-64+16)/(g.VY(M.width*.27,250,450)+16));M=Math.min(3,Math.floor((M.height-64)/((M.width-64-(B-1)*16)/B*.5625+70)));g.K7(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.D8(this.element,"ytp-modern-endscreen-limit-rows-"+M);g.ep(this.element,"ytp-modern-endscreen-single-item",B===1);g.ep(this.element,"ytp-modern-endscreen-row-0",M===0);B=this.table.element;B.ariaLive="polite";this.C.lZ(g.Bk(this.videoData));this.C instanceof DH&&Ou(this.C);g.ep(this.element,"ytp-endscreen-takeover",bM(this));uM(this);M=0;B.ariaBusy="true";q=O.length;for(D=0;D<q;D++){var C=D%q,K=this.stills[D];K||(K=new Fs(this.player),this.stills[D]=K,B.appendChild(K.element));C=O[C];if(K.suggestion!==
C){K.suggestion=C;var E=K.api.S();Mq(K,C,"hqdefault.jpg");if(g.dY(E)&&!K.api.G("web_player_log_click_before_generating_ve_conversion_params")){E=C.VS();var v={};g.uH(K.api,"addEmbedsConversionTrackingParams",[v]);E=g.ld(E,v);K.updateValue("url",E)}(C=(C=C.sessionData)&&C.itct)&&K.api.setTrackingParams(K.element,C)}M++}this.stills.length=M}};
g.e.onVideoDataChange=function(){var B=this.player.getVideoData(1);this.videoData!==B&&(B!=null&&g.Bk(B)?(this.videoData=B,this.rC()):this.player.hq("missg",{vid:(B==null?void 0:B.videoId)||"",cpn:(B==null?void 0:B.clientPlaybackNonce)||""}))};
g.e.uX=function(){return this.C.FR()};
g.e.ZP=function(B){B===1?(this.W=!1,this.B=this.videoData.clientPlaybackNonce,this.C.sJ(),this.vE&&this.rC()):(this.W=!0,this.vE&&bM(this)&&(B===2?this.C.DW():B===3&&this.C.vI()))};
g.e.U2=function(B){if(B){for(B=0;B<this.stills.length;B++)this.Z.logVisibility(this.stills[B].element,!0);this.ZP(1)}else this.B=null,this.W=!1;this.rC()};
g.e.Dh=function(){return this.vE&&bM(this)};g.z(Mtj,CS);Mtj.prototype.a4=function(){var B=this.player.getVideoData();this.C.update({profilePicture:B.profilePicture,author:B.author});this.subscribeButton.channelId=B.f7;var M=this.subscribeButton;B.subscribed?M.C():M.T()};g.z(Ja,g.T);Ja.prototype.select=function(){this.api.iC(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Ck||void 0)&&this.api.logClick(this.element)};
Ja.prototype.onClick=function(B){if(g.dY(this.api.S())&&this.api.G("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var M=this.suggestion.VS(),q={};g.I$(this.api,q);M=g.ld(M,q);g.Ei(M,this.api,B)}else g.oV(B,this.api,this.T,this.suggestion.sessionData||void 0)&&this.select()};
Ja.prototype.onKeyPress=function(B){switch(B.keyCode){case 13:case 32:B.defaultPrevented||(this.select(),B.preventDefault())}};
Ja.prototype.onVideoDataChange=function(){var B=this.api.getVideoData(),M=this.api.S();this.T=B.yN?!1:M.W};g.z(Aa,CS);g.e=Aa.prototype;g.e.create=function(){CS.prototype.create.call(this);var B=this.player.getVideoData();B&&(this.videoData=B);this.yl();this.T.V(this.player,"appresize",this.yl);this.T.V(this.player,"onVideoAreaChange",this.yl);this.T.V(this.player,"videodatachange",this.onVideoDataChange);this.T.V(this.player,"autonavchange",this.fS);this.T.V(this.player,"onAutonavCancelled",this.hw);B=this.videoData.autonavState;B!==this.U&&this.fS(B);this.T.V(this.element,"transitionend",this.bA)};
g.e.destroy=function(){g.gM(this.T);g.bZ(this.stills);this.stills=[];CS.prototype.destroy.call(this);g.C7(this.element,"ytp-show-tiles");this.D.stop();this.U=this.videoData.autonavState};
g.e.D9=function(){return this.videoData.autonavState!==1};
g.e.show=function(){var B=this.vE;CS.prototype.show.call(this);g.C7(this.element,"ytp-show-tiles");this.player.S().T?g.Rb(this.D):this.D.start();(this.K||this.W&&this.W!==this.videoData.clientPlaybackNonce)&&g.Gh(this.player,!1);Nq(this)?(zk(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.C.select(!0):this.C.DW():this.videoData.autonavState===3&&this.C.vI()):(g.Gh(this.player,!0),zk(this));B!==this.vE&&this.player.logVisibility(this.element,!0)};
g.e.hide=function(){var B=this.vE;CS.prototype.hide.call(this);this.C.vI();zk(this);B!==this.vE&&this.player.logVisibility(this.element,!1)};
g.e.bA=function(B){B.target===this.element&&this.yl()};
g.e.yl=function(){var B,M,q,D;var O=((B=this.videoData)==null?0:(M=B.suggestions)==null?0:M.length)?(q=this.videoData)==null?void 0:q.suggestions:[(D=this.videoData)==null?void 0:g.Bk(D)];if(O.length){g.D8(this.element,"ytp-endscreen-paginate");var C=this.Z.yR(!0,this.Z.isFullscreen());if(B=g.$G(this.Z))B=B.UN()?48:32,C.width-=B*2;var K=C.width/C.height;D=96/54;M=B=2;var E=Math.max(C.width/96,2),v=Math.max(C.height/54,2);q=O.length;var F=q*4;for(F-=4;F>0&&(B<E||M<v);){var b=B/2,u=M/2,J=B<=E-2&&F>=
u*4,A=M<=v-2&&F>=b*4;if((b+1)/u*D/K>K/(b/(u+1)*D)&&A)F-=b*4,M+=2;else if(J)F-=u*4,B+=2;else if(A)F-=b*4,M+=2;else break}D=!1;F>=12&&q*4-F<=6&&(M>=4||B>=4)&&(D=!0);F=B*96;E=M*54;K=F/E<K?C.height/E:C.width/F;K=Math.min(K,2);F=Math.floor(Math.min(C.width,F*K));E=Math.floor(Math.min(C.height,E*K));C=this.table.element;C.ariaLive="polite";g.wN(C,F,E);g.HV(C,{marginLeft:F/-2+"px",marginTop:E/-2+"px"});this.C.lZ(g.Bk(this.videoData));this.C instanceof DH&&Ou(this.C);g.ep(this.element,"ytp-endscreen-takeover",
Nq(this));zk(this);F+=4;E+=4;K=0;C.ariaBusy="true";for(v=0;v<B;v++)for(b=0;b<M;b++)if(u=K,A=0,D&&v>=B-2&&b>=M-2?A=1:b%2===0&&v%2===0&&(b<2&&v<2?b===0&&v===0&&(A=2):A=2),u=g.gC(u+this.B,q),A!==0){J=this.stills[K];J||(J=new Ja(this.player),this.stills[K]=J,C.appendChild(J.element));var N=Math.floor(E*b/M),y=Math.floor(F*v/B),k=Math.floor(E*(b+A)/M)-N-4,m=Math.floor(F*(v+A)/B)-y-4;g.fm(J.element,y,N);g.wN(J.element,m,k);g.HV(J.element,"transitionDelay",(b+v)/20+"s");g.ep(J.element,"ytp-videowall-still-mini",
A===1);g.ep(J.element,"ytp-videowall-still-large",A>2);A=Math.max(m,k);g.ep(J.element,"ytp-videowall-still-round-large",A>=256);g.ep(J.element,"ytp-videowall-still-round-medium",A>96&&A<256);g.ep(J.element,"ytp-videowall-still-round-small",A<=96);u=O[u];J.suggestion!==u&&(J.suggestion=u,A=J.api.S(),N=g.qv(J.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",Mq(J,u,N),g.dY(A)&&!J.api.G("web_player_log_click_before_generating_ve_conversion_params")&&(A=u.VS(),N={},g.uH(J.api,"addEmbedsConversionTrackingParams",
[N]),A=g.ld(A,N),J.updateValue("url",A)),(u=(u=u.sessionData)&&u.itct)&&J.api.setTrackingParams(J.element,u));K++}C.ariaBusy="false";g.ep(this.element,"ytp-endscreen-paginate",K<q);for(O=this.stills.length-1;O>=K;O--)B=this.stills[O],g.DT(B.element),g.FE(B);this.stills.length=K}};
g.e.onVideoDataChange=function(){var B=this.player.getVideoData(1);this.videoData!==B&&(B!=null&&g.Bk(B)?(this.B=0,this.videoData=B,this.yl()):this.player.hq("missg",{vid:(B==null?void 0:B.videoId)||"",cpn:(B==null?void 0:B.clientPlaybackNonce)||""}))};
g.e.vG=function(){this.B+=this.stills.length;this.yl()};
g.e.Cc=function(){this.B-=this.stills.length;this.yl()};
g.e.uX=function(){return this.C.FR()};
g.e.fS=function(B){B===1?(this.K=!1,this.W=this.videoData.clientPlaybackNonce,this.C.sJ(),this.vE&&this.yl()):(this.K=!0,this.vE&&Nq(this)&&(B===2?this.C.DW():B===3&&this.C.vI()))};
g.e.hw=function(B){if(B){for(B=0;B<this.stills.length;B++)this.Z.logVisibility(this.stills[B].element,!0);this.fS(1)}else this.W=null,this.K=!1;this.yl()};
g.e.Dh=function(){return this.vE&&Nq(this)};g.z($w,CS);$w.prototype.hasSuggestions=function(){var B;return(B=this.C)==null?void 0:B.hasSuggestions()};
$w.prototype.show=function(){if(this.player.getPlayerState()!==3){CS.prototype.show.call(this);var B=this.T;if(B){var M=this.C.hasSuggestions();g.ep(this.element,"ytp-shorts-branded-ui",M);M?B.show():B.hide()}var q;(q=g.$G(this.player))==null||q.uE(!0);this.player.logVisibility(this.element,!0);this.watchButton.L3(!0)}};
$w.prototype.hide=function(){CS.prototype.hide.call(this);var B;(B=g.$G(this.player))==null||B.uE(!1);this.player.logVisibility(this.element,!1);this.watchButton.L3(!1)};g.z(Cju,g.v_);g.e=Cju.prototype;g.e.Jp=function(){var B=this.player.getVideoData(),M=B.mutedAutoplay&&(B.limitedPlaybackDurationInSeconds>0||B.endSeconds>0||B.mutedAutoplayDurationMode!==2);if((this.player.isEmbedsShortsMode()||this.T)&&!M)return!0;var q;var D=!!((B==null?0:g.Bk(B))||(B==null?0:(q=B.suggestions)==null?0:q.length));D=!qWM(this.player)||D;B=B.T2;q=this.player.fP();return D&&!B&&!q&&!M};
g.e.Dh=function(){return this.endScreen.Dh()};
g.e.RPq=function(){return this.Dh()?this.endScreen.uX():!1};
g.e.eY=function(){this.player.VI("endscreen");g.v_.prototype.eY.call(this)};
g.e.load=function(){var B=this.player.getVideoData();var M=B.transitionEndpointAtEndOfStream;if(M&&M.videoId){var q=this.player.M7().wF.get("heartbeat"),D=g.Bk(B);!D||M.videoId!==D.videoId||B.J8?(this.player.iC(M.videoId,void 0,void 0,!0,!0,M),q&&q.x9("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),B=!0):B=!1}else B=!1;B||(g.v_.prototype.load.call(this),this.endScreen.show())};
g.e.unload=function(){g.v_.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.e.onCueRangeEnter=function(B){this.Jp()&&(this.endScreen.created||this.endScreen.create(),B.getId()==="load"&&this.load())};
g.e.onCueRangeExit=function(B){B.getId()==="load"&&this.loaded&&this.unload()};
g.e.onVideoDataChange=function(){Obj(this);this.W&&DEN(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.C?this.endScreen=new eU(this.player):this.endScreen=new Aa(this.player),g.p(this,this.endScreen),g.Hs(this.player,this.endScreen.element,4))};g.Ep("endscreen",Cju);})(_yt_player);
